// { img, price, fav, title, desc, loc, date }
export default [
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'Monitor',
    desc: 'Its a monitor',
    loc: 'cairo',
    date: '100',
  },
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'Monitor',
    desc: 'Its a monitor',
    loc: 'cairo',
    date: '100',
  },
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'Monitor',
    desc: 'Its a monitor',
    loc: 'cairo',
    date: '100',
  },
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'Monitor',
    desc: 'Its a monitor',
    loc: 'cairo',
    date: '100',
  },
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'Monitor',
    desc: 'Its a monitor',
    loc: 'cairo',
    date: '100',
  },
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'Monitor',
    desc: 'Its a monitor',
    loc: 'cairo',
    date: '100',
  },
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'Monitor',
    desc: 'Its a monitor',
    loc: 'cairo',
    date: '100',
  },
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'Monitor',
    desc: 'Its a monitor',
    loc: 'cairo',
    date: '100',
  },
];
