// { img, price, fav, title, desc, loc, date }
export default [
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'monitor',
    desc: 'monitor_des',
    loc: 'yemen',
    date: '100',
  },
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'monitor',
    desc: 'monitor_des',
    loc: 'yemen',
    date: '100',
  },
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'monitor',
    desc: 'monitor_des',
    loc: 'yemen',
    date: '100',
  },
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'monitor',
    desc: 'monitor_des',
    loc: 'yemen',
    date: '100',
  },
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'monitor',
    desc: 'monitor_des',
    loc: 'yemen',
    date: '100',
  },
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'monitor',
    desc: 'monitor_des',
    loc: 'yemen',
    date: '100',
  },
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'monitor',
    desc: 'monitor_des',
    loc: 'yemen',
    date: '100',
  },
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'monitor',
    desc: 'monitor_des',
    loc: 'yemen',
    date: '100',
  },
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'monitor',
    desc: 'monitor_des',
    loc: 'yemen',
    date: '100',
  },
  {
    img: '/products-imgs/monitor.jpg',
    price: 30,
    fav: false,
    title: 'monitor',
    desc: 'monitor_des',
    loc: 'yemen',
    date: '100',
  },
];
